import React from "react";
import { render } from "@testing-library/react";
import { T } from "gt-react";
import { buildTranslations, gtKey } from "./gtManualTranslations";
import { documentExpirationEntries } from "./locales/documentExpirationEntries";

describe("hand-written GT translations", () => {
    it("reproduces a key that gt translate produced", () => {
        // Taken from a real pl.json generated by `npx gt translate` for this view.
        // If this drifts, the local hash no longer matches GT's and every
        // hand-written translation silently falls back to English.
        expect(gtKey("Set max number of documents to process in a single run")).toBe("28c578aeb4b12af3");
    });

    it("keys every entry by its content hash", () => {
        const translations = buildTranslations(documentExpirationEntries, "pl");

        expect(translations[gtKey("Document Expiration")]).toBe("Wygasanie dokumentów");
        expect(translations[gtKey("Save")]).toBe("Zapisz");
        expect(Object.keys(translations)).toHaveLength(documentExpirationEntries.length);
    });

    it("omits locales with no translation so GT falls back to English", () => {
        expect(buildTranslations(documentExpirationEntries, "de")).toEqual({});
    });

    it("produces distinct keys per source string", () => {
        const keys = documentExpirationEntries.map((entry) => gtKey(entry.source));

        expect(new Set(keys).size).toBe(keys.length);
    });

    it("renders English when no translations are supplied", () => {
        const { container } = render(
            <T>
                <span>Save</span>
            </T>
        );

        expect(container.textContent).toContain("Save");
    });
});
